//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebserviceTestClient.SearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchService.ISearchService")]
    public interface ISearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Search", ReplyAction="http://tempuri.org/ISearchService/SearchResponse")]
        bool Search(string userEmail, string name, System.Nullable<byte> minAge, System.Nullable<byte> maxAge, bool canBeFemale, bool canBeMale, System.Nullable<short> minHeight, System.Nullable<short> maxHeight, System.Nullable<short> minWeight, System.Nullable<short> maxWeight, string nationality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Search", ReplyAction="http://tempuri.org/ISearchService/SearchResponse")]
        System.Threading.Tasks.Task<bool> SearchAsync(string userEmail, string name, System.Nullable<byte> minAge, System.Nullable<byte> maxAge, bool canBeFemale, bool canBeMale, System.Nullable<short> minHeight, System.Nullable<short> maxHeight, System.Nullable<short> minWeight, System.Nullable<short> maxWeight, string nationality);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceChannel : WebserviceTestClient.SearchService.ISearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<WebserviceTestClient.SearchService.ISearchService>, WebserviceTestClient.SearchService.ISearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Search(string userEmail, string name, System.Nullable<byte> minAge, System.Nullable<byte> maxAge, bool canBeFemale, bool canBeMale, System.Nullable<short> minHeight, System.Nullable<short> maxHeight, System.Nullable<short> minWeight, System.Nullable<short> maxWeight, string nationality) {
            return base.Channel.Search(userEmail, name, minAge, maxAge, canBeFemale, canBeMale, minHeight, maxHeight, minWeight, maxWeight, nationality);
        }
        
        public System.Threading.Tasks.Task<bool> SearchAsync(string userEmail, string name, System.Nullable<byte> minAge, System.Nullable<byte> maxAge, bool canBeFemale, bool canBeMale, System.Nullable<short> minHeight, System.Nullable<short> maxHeight, System.Nullable<short> minWeight, System.Nullable<short> maxWeight, string nationality) {
            return base.Channel.SearchAsync(userEmail, name, minAge, maxAge, canBeFemale, canBeMale, minHeight, maxHeight, minWeight, maxWeight, nationality);
        }
    }
}
